#!/usr/bin/env php
<?php

require __DIR__ . '/../../../autoload.php';

use Symfony\Component\Console\Application;
use App\Console\Commands;

// Create a new Symfony Console application
$application = new Application();

// Register the publishResources command
Commands::publishResources();